# Generated by Django 3.0.5 on 2020-04-27 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babies', '0002_baby_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Siesta', 'Siesta'), ('Pacha', 'Pacha'), ('Pipi', 'Pipi'), ('Popo', 'Popo'), ('Pecho', 'Pecho')], max_length=50)),
                ('comment', models.CharField(max_length=250, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='babies.Baby')),
            ],
        ),
    ]
